# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentsAPI', '0003_auto_20160621_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='studentsAPI.Group', verbose_name='Група'),
        ),
    ]
